apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sklonger.fullname" . }}-config
  labels:
    {{- include "sklonger.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.config.port | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  BLUESKY_API_URL: {{ .Values.config.blueskyApiUrl | quote }}
  REQUEST_TIMEOUT_SECONDS: {{ .Values.config.requestTimeoutSeconds | quote }}
